name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Bước 1: Checkout mã nguồn từ repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Bước 2: Thiết lập Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Bước 3: Đăng nhập vào Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Bước 4: Build và đẩy Docker image lên Docker Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: innosphere-be/Dockerfile
        push: true
        tags: tinlek17/innospherebe:latest

    # Bước 5: Triển khai lên VPS qua SSH
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.VPS_HOST }}  # Đã cập nhật IP: 103.163.24.72
        username: ${{ secrets.VPS_USERNAME }}  # Giả định là root, thay nếu khác
        password: ${{ secrets.VPS_PASSWORD }}
        port: 22
        script: |
          # Dừng container hiện tại
          cd /code/innosphere-be
          docker-compose down
          # Kéo image mới từ Docker Hub
          docker pull tinlek17/innospherebe:latest
          # Chạy lại ứng dụng
          docker-compose up -d
